table fact_Sales
	lineageTag: a6665007-a901-4174-9481-18c5078be513

	column Segment
		dataType: string
		lineageTag: c71c89d9-e3b5-4631-8e6f-6de57872816b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 89679c2a-a181-4b03-9d4e-f228003618c2
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: af6d171d-fb15-4749-8cf4-8af0968e9597
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 7e9c914e-95ea-4d5e-b540-c6093a646f8b
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: #,0
		lineageTag: b8d70b74-ddff-4a3d-99da-d211c4dd10a8
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Price'
		dataType: int64
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3cfc4ec2-c715-4118-b61a-f270e15df1af
		summarizeBy: average
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = User

	column 'Sale Price'
		dataType: int64
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 07df746d-a294-46ae-8c5a-e2cf1fb77681
		summarizeBy: average
		sourceColumn: Sale Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Gross Sales'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e2d3b693-27ec-4955-a504-165c5ffc2751
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

	column Discounts
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1184832e-8167-473b-a621-b3a73df821ef
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

	column ' Sales'
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5739fb83-82c6-4710-b31d-4afa5d3f918c
		summarizeBy: sum
		sourceColumn: " Sales"

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: eb28b57b-9189-4e52-aba6-852cfdfa417c
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1a80daf0-11c3-4b54-baf8-9330b6734ae7
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 839ef61a-0aa9-4850-b05f-20030e437ddb
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 888ac41f-0545-4d73-9d91-b90afc062294
		summarizeBy: sum
		sourceColumn: Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		isHidden
		lineageTag: 0188250c-2100-421d-9063-a63d1dc0cae6
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f5debe82-3329-4c28-aa9c-b51fa23eaf5a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Test Column' = SUMX(fact_Sales, fact_Sales[ Sales] - fact_Sales[COGS])
		lineageTag: 6cd23792-082b-4522-b0c9-23d95f504e88
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_Sales = m
		mode: import
		source =
				let
				    Fonte = Table.Combine({Base_2013_2014, Base_2015_2016}),
				    #"Filtered Rows" = Table.SelectRows(Fonte, each [Date] <> null and [Date] <> ""),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","United States of America","USA",Replacer.ReplaceText,{"Country"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

