table _Measures
	lineageTag: b2eda992-ab67-4ff3-ba27-0e396e4556bd

	measure '# Customers (w/ Sales)' = DISTINCTCOUNT('Sales'[CustomerKey])
		formatString: #,##0
		lineageTag: 4ec872f0-a42d-4aa9-bf6b-1ca7c4916336

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

